### DISCUSSION TITLE
[Feature Request] Option to disable Vertical Bar when "Improve the style of your lists" is checked

### DISCUSSION THREAD

**Discussion by morgenman** [vslinko/obsidian-outliner#222] [Archive]
Hey, I love this plugin but haven't been able to use it since it makes it a bit cluttered. 
For one, several other addons/themes add vertical bars, sometimes without the option to disable them. 

Also, (my tab size is 4) on mine there are two vertical bars for each indent. 

4 is the recommended tab size, so I'm not sure why it's happening, but rather than submit an issue for that, I would rather have the option to just turn them off entirely. 

Here is what my screen looks like with the checkbox enabled:
![image](https://user-images.githubusercontent.com/3505950/138715029-51db0b68-9806-4a64-8a71-8b135f132a86.png)

Here is what it looks like without the checkbox enabled:
![image](https://user-images.githubusercontent.com/3505950/138715322-3151d050-bccc-44fe-9414-d408c7af862f.png)

**Comment by ghost** [comment]
I have the same duplication of vertical lines. Base theme.

- Disabled all community AND core plugins, still have the double lines
- disabled CSS snippet and the double vertical lines went away

This is the content of my CSS snippet
```css
.markdown-source-view
{
    font-family: 'iA Writer Mono S', Consolas, monospace;
}
```

Conclusion: monospace font breaks outliner display

This seems like a bug rather than feature enhancement

**Comment by timrichard** [comment]
Hi, I was just about to leave a bug report, but a search turned up this thread.

My CSS snippet was 

```
.markdown-source-view {
        font-family: 'Source Code Pro', monospace;
}
```

I can confirm the report from @LeslieP-TX that commenting out only the font CSS removes the issue. 

It would be really great monospace fonts could be supported in Outline enhanced list view.
I could be wrong, but I have a feeling this could be a fairly recent thing because I've been using my snippet and the monospace font together for a while. I upgraded all my community plugins today.

Thanks in advance for any feedback...

 - OS: MacOS
 - Obsidian Version: v0.12.19
 - Outliner Version: v1.4.0

**Comment by timrichard** [comment]
Hi,
Just been trying a couple of things, and I got the verticals to line up with my monospace font by changing this line....

https://github.com/vslinko/obsidian-outliner/blob/305af20a3f6e5471b42962c322ba797c49bd7626/styles.css#L40

to 

`background-size: 4ch 1px;`

My tab size is 4.

**Comment by ghost** [comment]
> Hi, Just been trying a couple of things, and I got the verticals to line up with my monospace font by changing this line....
> 
> https://github.com/vslinko/obsidian-outliner/blob/305af20a3f6e5471b42962c322ba797c49bd7626/styles.css#L40
> 
> to
> 
> `background-size: 4ch 1px;`
> 
> My tab size is 4.

That makes sense - I have just learned that "ch" is the width of a zero, and in the standard proportional font, 1.8 ch is probably about the width of 4 spaces, whereas with a monospace font, 4 spaces is 4 zeros. I thought I was "css informed" but apparently not. 

So, my snippets file now contains:
```css
.outliner-plugin-bls .markdown-source-view .CodeMirror-line .cm-hmd-list-indent::before
{
background-size: 4ch 1px;
}
```
and it seems to work right. 

Thanks @timrichard !!!

**Comment by ghost** [comment]
FYI - I just added another little tweak in my snippets file to fix the problem with hanging indents, so here is what the snippets file has now.

```css
/* Monospace font in editor view */
.markdown-source-view
	{
    font-family: 'iA Writer Mono S', Consolas, monospace;
	}

/* Outliner Plugin fix duplicate vertical guidelines */
.outliner-plugin-bls .markdown-source-view .CodeMirror-line .cm-hmd-list-indent::before
	{
	background-size: 4ch 1px;
	}

/* Outliner Plugin fix hanging indent */
.outliner-plugin-bls .markdown-source-view .cm-s-obsidian span.cm-formatting-list
	{
	letter-spacing: inherit;
	}
```
