### DISCUSSION TITLE
Vertical lines are't working whith the Minimal Theme.

### DISCUSSION THREAD

**Discussion by ghost** [vslinko/obsidian-outliner#417] [Ideas]
**Describe the bug**
Vertical lines are't working whith the Minimal Theme.

**To Reproduce**
Wen i start the Minimal Theme vertical lines immidiatly stop working (i can't clicking on them).

**Desktop (please complete the following information):**
 - Windows 11
 - Obsidian Version: 1.1.9
 - Minimal Theme 6.2.0

**Comment by atnoir** [comment]
same issue. do you find any theme that is compatible with this vertical line feature? for me, it only works in the default theme, but those lines are all misaligned. I tried several themes such as topaz and things, but none of them worked (the lines are just not clickable). thanks.

**Comment by vslinko** [comment]
You are correct, only the default theme is supported. Updated the disclaimer in the README.

**Comment by jrsmroz** [comment]
It works only with default theme because there is an explicit check in the code that prevents the feature to run on non default themes.
```ts
const shouldExists = this.obsidianSettings.isDefaultThemeEnabled() &&
    this.settings.verticalLines;
```

That can be patched locally if one want to try it on minimal theme.

The alignment of the lines can be corrected by setting margin on `outliner-plugin-list-lines-scroller` in the snippet. I'm not sure about the values. But I did get promising results with the snippet:

```css

.markdown-source-view.mod-cm6.is-readable-line-width
.outliner-plugin-list-lines-scroller {
    margin-top: 1.18em;
    width: 100%;
    scroll-padding-block-end: var(--status-bar-scroll-padding);
    scrollbar-gutter: stable;
}


.markdown-source-view.mod-cm6.is-readable-line-width
.outliner-plugin-list-lines-content-container {
    max-width: min(
        var(--line-width),
        var(--max-width)
    );
    margin-inline-start: var(--content-margin) !important;
}

.outliner-plugin-list-line {
    margin-left: calc(var(--list-padding-inline-start) + 1px);
    background-image: linear-gradient(
        to right,
        var(--bg3) 0.5px,
        transparent 0.5px
    );
    border-radius: 10px;
}

.outliner-plugin-list-line:hover {
    background: var(--bg3);
}
```
