### ISSUE TITLE
[BUG] Bullet margin issue when “Improve the style of your lists” is enabled

### ISSUE THREAD

**Issue by mdrain** [vslinko/obsidian-outliner#371]
**Describe the bug**
When the “Improve the style of your lists” option is enabled, clicking in the first line of a bulleted list and pressing the Home button takes the user to the space between the bullet and the first character of the line.

**To Reproduce**
1. Enable "Improve the style of your lists" in Outliner options
2. Go to a bulleted list
3. Click within the first line of a bulleted line
4. Press the Home button

**Expected behavior**
The cursor should go to the position of the first character in the line.

**Screenshots**
![image](https://user-images.githubusercontent.com/24597626/197401551-557ac591-c773-4b9e-b514-624e01dc374e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Obsidian Version: 1.0.2
 - Obsidian Theme: Default

**Comment by Fyzu** [comment]
What is `home` button?

**Comment by mdrain** [comment]
Home button on keyboard.

**Comment by mdrain** [comment]
This appears to be fixed by adding the following CSS snippet:

```css
.outliner-plugin-better-bullets .cm-formatting-list-ul {
  margin-right: inherit;
}

.outliner-plugin-better-bullets .list-bullet {
  margin-right: 0.3em;
}
```

**Comment by charlie17** [comment]
@mdrain nice, I had this issue and that fixed it

**Comment by Robyer** [comment]
> This appears to be fixed by adding the following CSS snippet:
> 
> ```css
> .outliner-plugin-better-bullets .cm-formatting-list-ul {
>   margin-right: inherit;
> }
> 
> .outliner-plugin-better-bullets .list-bullet {
>   margin-right: 0.3em;
> }
> ```

@mdrain This works, but it creates another issue. The text jumps a bit left as the margin disappears when cursor is at the beginning of the line. This is better noticeable when the "Stick the cursor to the content" option is disabled, but issue is present even when enabled.

![image](https://user-images.githubusercontent.com/359173/207388007-3e538f96-922f-464b-8f7b-8547de88c8c7.png)

Maybe better solution would be to remove the `margin-right` on the bullet altogether, and use `margin-left` (or `padding-left`) on the text itself?

**Comment by xeor** [comment]
Looks like margin-left or padding-left on the text also gives the same problem. What seams to work (at least on my test) is setting `text-indent: 0.3em;` on `.markdown-source-view.mod-cm6 .cm-line > *` (the text itself), and remove the `padding-left` added by the outliner.

So;

```css
.outliner-plugin-better-bullets .cm-formatting-list-ul {
    margin-right: 0 !important;
}

.markdown-source-view.mod-cm6 .cm-line>* {
    text-indent: 0.3em;
}
```

**Comment by Robyer** [comment]
@xeor I'll try this when I have some time, but I wanted to point out that using the universal selector (the *) at the right side will cause worse performance. So finding more concrete selector would be beneficial.

**Comment by xeor** [comment]
Ok, cool.. I just took the selector that was already used for the part I needed. It is defined in obsidian's own app.css and originally is set to:

```css
.markdown-source-view.mod-cm6 .cm-line > * {
  text-indent: 0;
}
```
